version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/pro/real_build/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # nginx와 연결되어 있지 않지만 실행중이던 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # nginx와 연결되어 있지 않은 port로 새 버전의 스프링부트 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user